// import './constants/contacts.js';
// import './db/db.json';
// import './scripts/addOneContact.js';
// import './scripts/countContacts.js';
// import './scripts/generateContacts.js';
// import './scripts/getAllContacts.js';
// import './scripts/removeAllContacts.js';
// import './scripts/removeLastContact.js';
import './utils/createFakeContact.js';
import './utils/readContacts.js';
import './utils/writeContacts.js';
